In [31]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [32]:
df = pd.read_csv('Fifa_Worldcup_2022.csv')
df.head(5)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [33]:
# code here
df = pd.read_csv('Fifa_Worldcup_2022.csv')
all_teams = df['Team'].unique()
store = {}

# Step2
for team in all_teams:
    all_records = df[(df['Team'] == team) | (df['Against'] == team)]
    percantage = (all_records['On Target'].sum() / all_records['Total Attempts'].sum()) * 100
    store[team] = round(percantage, 2)

sorted_store = dict(sorted(store.items(), key=lambda x: x[1], reverse=True))
sorted_store

{'Argentina': np.float64(42.86),
 'Serbia': np.float64(42.68),
 'Switzerland': np.float64(41.56),
 'Cameroon': np.float64(41.43),
 'Brazil': np.float64(41.13),
 'Ecuador': np.float64(40.82),
 'Ghana': np.float64(40.58),
 'England': np.float64(38.46),
 'Qatar': np.float64(38.0),
 'Iran': np.float64(37.14),
 'Netherlands': np.float64(37.04),
 'Croatia': np.float64(37.04),
 'Germany': np.float64(36.96),
 'Portugal': np.float64(36.94),
 'Saudi Arabia': np.float64(36.84),
 'Spain': np.float64(36.49),
 'Costa Rica': np.float64(36.49),
 'Poland': np.float64(35.92),
 'United States': np.float64(35.9),
 'France': np.float64(35.54),
 'Korea Republic': np.float64(35.05),
 'Canada': np.float64(33.33),
 'Senegal': np.float64(32.95),
 'Tunisia': np.float64(32.2),
 'Australia': np.float64(31.82),
 'Mexico': np.float64(31.34),
 'Wales': np.float64(30.88),
 'Japan': np.float64(30.1),
 'Belgium': np.float64(29.87),
 'Uruguay': np.float64(29.51),
 'Denmark': np.float64(28.57),
 'Morocco': np.float64(25.19)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [34]:
# code here
df["Team"].value_counts().rank(method="first")

Team
Morocco           29.0
Croatia           30.0
Argentina         31.0
France            32.0
England           25.0
Brazil            26.0
Netherlands       27.0
Portugal          28.0
Poland            17.0
Japan             18.0
Switzerland       19.0
Australia         20.0
Korea Republic    21.0
United States     22.0
Senegal           23.0
Spain             24.0
Cameroon           1.0
Uruguay            2.0
Belgium            3.0
Ghana              4.0
Canada             5.0
Qatar              6.0
Costa Rica         7.0
Germany            8.0
Ecuador            9.0
Mexico            10.0
Tunisia           11.0
Denmark           12.0
Saudi Arabia      13.0
Wales             14.0
Iran              15.0
Serbia            16.0
Name: count, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [35]:
# code here
df.info()
df.describe()
df.isna().sum()
df.drop_duplicates(inplace = True)
df.drop(columns=[ "Match No.", "Red Cards", "Pts"], inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [36]:
# code here
df["Rank"]=df["Team"].rank(method="first")
df["Rank"]=df["Rank"].astype(np.int16)
df.set_index("Rank", inplace=True)
df.sort_index(inplace=True)
df

,Sl. No,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,9,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,6,10,4,12,4,5,8,18,91,27,195,127,10,8,0,7,10,593,525,36,15,9,21,1
2,47,Argentina,Mexico,C,2,50,1,1,2,5,2,3,2,3,10,6,2,4,12,89,2,150,100,10,5,1,15,2,533,464,14,2,4,23,0
3,78,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,11,0,862,814,22,5,9,5,0
4,99,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,8,4,711,635,6,1,1,15,0
5,116,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,18,2,603,511,16,4,8,30,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,64,Uruguay,Portugal,H,0,35,0,0,0,10,3,6,6,4,13,8,4,5,9,94,6,150,86,17,11,2,16,0,390,306,18,5,2,13,0
125,90,Uruguay,Ghana,H,2,39,2,0,1,12,7,5,7,5,7,2,13,3,17,186,14,186,124,24,14,3,11,2,446,361,15,4,2,20,0
126,8,Wales,United States,B,1,39,1,0,0,7,3,3,5,2,7,2,5,2,7,73,9,174,103,17,8,2,10,1,409,321,15,6,3,15,1
127,33,Wales,Iran,B,0,51,0,0,0,10,3,4,5,5,18,3,8,11,13,101,13,208,129,17,8,1,9,2,508,413,20,5,2,12,0
128,69,Wales,England,B,0,33,0,0,0,7,1,3,1,6,7,1,2,0,4,46,1,104,55,4,1,2,16,1,325,261,4,1,1,10,0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [37]:
# code here
d1=pd.read_csv("dataset1.csv")
d1.dropna(subset=["Age"],inplace=True)
d1
d2=pd.read_csv("dataset2.csv")
d2["Age"]=d2["Age"].fillna(20,inplace=True)
d2

/var/folders/qh/gj7grb5121zdf7b2nvgr37km0000gn/T/ipykernel_28506/3227472526.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d2["Age"]=d2["Age"].fillna(20,inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,None,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,None,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,None,0,0,370376,7.7500,NaN,Q

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [38]:
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
matches=pd.read_csv(ipl_matches)
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [39]:
# code here
matches = matches[~matches.WinningTeam.isna()]
new_df = pd.DataFrame()
teams = matches.Team1.unique()
data = []
for team in teams:
    played = matches[(matches.Team1 == team) | (matches.Team2 == team)].shape[0]
    wins = matches[matches.WinningTeam == team].shape[0]
    home_win = matches[(matches.WinningTeam == team) & (matches.Team1 == team)].shape[0] / matches[matches.Team1 == team].shape[0] * 100
    away_win = matches[(matches.WinningTeam == team) & (matches.Team2 == team)].shape[0] / matches[matches.Team2 == team].shape[0] * 100
    data.append([team, played, wins/played*100, home_win, away_win])
new_df[["Team", "Matches Played", "Win Percentage", "Home Win Percentage", "Away Win Percentage"]] = data
new_df.sort_values("Win Percentage", inplace=True, ascending=False)
new_df

,Team,Matches Played,Win Percentage,Home Win Percentage,Away Win Percentage
5,Gujarat Titans,16,75.0,57.142857,88.888889
12,Rising Pune Supergiant,16,62.5,71.428571,55.555556
6,Lucknow Super Giants,15,60.0,87.5,28.571429
4,Chennai Super Kings,208,58.173077,58.558559,57.731959
3,Delhi Capitals,63,57.142857,51.724138,61.764706
9,Mumbai Indians,231,56.709957,58.035714,55.462185
7,Kolkata Knight Riders,223,51.121076,53.333333,49.152542
0,Rajasthan Royals,190,50.526316,55.05618,46.534653
2,Sunrisers Hyderabad,152,49.342105,52.173913,46.987952
1,Royal Challengers Bangalore,223,48.878924,49.593496,48.0
8,Punjab Kings,28,46.428571,38.888889,60.0
10,Kings XI Punjab,190,46.315789,46.73913,45.918367
13,Gujarat Lions,30,43.333333,31.25,57.142857
17,Kochi Tuskers Kerala,14,42.857143,42.857143,42.857143
11,Delhi Daredevils,159,42.138365,45.238095,38.666667
16,Deccan Chargers,75,38.666667,33.333333,44.444444
14,Rising Pune Supergiants,14,35.714286,28.571429,42.857143
15,Pune Warriors,45,26.666667,26.086957,27.272727

###`Q-7:` Venues with most "no result" matches.

In [40]:
# code here
matches[matches.WonBy=="NoResults"].Venue.value_counts()

Series([], Name: count, dtype: int64)

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [43]:
# code here
store = {}
matches.reset_index(drop=True, inplace=True)

for i in range(df.shape[0]):
    for single_player in matches.loc[i, 'Team1Players'][1:-1].split(", "):
        player = single_player.strip("'")
        if player in store:
            store[player] += 1
        else:
            store[player] = 1
    
    for single_player in matches.loc[i, 'Team2Players'][1:-1].split(", "):
        player = single_player.strip("'")
        if player in store:
            store[player] += 1
        else:
            store[player] = 1

# Sorting the dictonary
dict(sorted(store.items(), key = lambda x: x[1], reverse = True))

{'Shubman Gill': 31,
 'F du Plessis': 31,
 'KD Karthik': 31,
 'SV Samson': 30,
 'D Padikkal': 30,
 'YS Chahal': 30,
 'R Ashwin': 29,
 'R Tewatia': 29,
 'Mohammed Shami': 29,
 'V Kohli': 29,
 'RA Tripathi': 29,
 'S Dhawan': 29,
 'RR Pant': 29,
 'SN Thakur': 29,
 'RD Gaikwad': 29,
 'MS Dhoni': 29,
 'N Rana': 29,
 'SO Hetmyer': 28,
 'TA Boult': 28,
 'Rashid Khan': 28,
 'HV Patel': 28,
 'Mohammed Siraj': 28,
 'Avesh Khan': 28,
 'K Rabada': 28,
 'AT Rayudu': 28,
 'SP Narine': 28,
 'R Parag': 27,
 'KL Rahul': 27,
 'GJ Maxwell': 26,
 'DJ Hooda': 26,
 'JJ Bumrah': 26,
 'CV Varun': 26,
 'M Prasidh Krishna': 25,
 'HH Pandya': 25,
 'DA Miller': 25,
 'Shahbaz Ahmed': 25,
 'Q de Kock': 25,
 'KH Pandya': 25,
 'N Pooran': 25,
 'Arshdeep Singh': 25,
 'AR Patel': 25,
 'RG Sharma': 25,
 'RA Jadeja': 25,
 'MA Agarwal': 24,
 'PP Shaw': 24,
 'MM Ali': 24,
 'JC Buttler': 23,
 'Ravi Bishnoi': 23,
 'B Kumar': 23,
 'KS Williamson': 23,
 'KA Pollard': 23,
 'Abhishek Sharma': 22,
 'Ishan Kishan': 22,
 'VR Iyer': 22,
 'SS Iyer': 22,
 'AD Russell': 22,
 'RD Chahar': 22,
 'LH Ferguson': 21,
 'JR Hazlewood': 21,
 'Mustafizur Rahman': 21,
 'YBK Jaiswal': 20,
 'MP Stoinis': 20,
 'AK Markram': 20,
 'DJ Bravo': 20,
 'SA Yadav': 20,
 'LS Livingstone': 19,
 'JO Holder': 19,
 'Lalit Yadav': 19,
 'S Dube': 19,
 'WP Saha': 18,
 'PWH de Silva': 18,
 'M Shahrukh Khan': 18,
 'DA Warner': 18,
 'Umran Malik': 17,
 'KK Ahmed': 17,
 'JM Bairstow': 16,
 'RV Uthappa': 16,
 'C Sakariya': 16,
 'Shivam Mavi': 15,
 'EJG Morgan': 15,
 'R Powell': 14,
 'Kuldeep Yadav': 14,
 'A Nortje': 14,
 'Tilak Varma': 14,
 'DL Chahar': 14,
 'Washington Sundar': 13,
 'DR Sams': 13,
 'Mukesh Choudhary': 13,
 'A Badoni': 13,
 'AB de Villiers': 13,
 'PVD Chameera': 12,
 'JM Sharma': 12,
 'Harpreet Brar': 12,
 'RP Meredith': 12,
 'UT Yadav': 12,
 'TG Southee': 12,
 'MK Pandey': 12,
 'RM Patidar': 11,
 'MK Lomror': 11,
 'E Lewis': 11,
 'T Natarajan': 11,
 'Sandeep Sharma': 11,
 'JD Unadkat': 11,
 'Abdul Samad': 11,
 'SK Raina': 11,
 'MS Wade': 10,
 'Shashank Singh': 10,
 'KS Bharat': 10,
 'PJ Cummins': 10,
 'M Ashwin': 10,
 'Anuj Rawat': 10,
 'CH Morris': 10,
 'Yash Dayal': 9,
 'Mohsin Khan': 9,
 'AS Joseph': 9,
 'TH David': 9,
 'S Kaul': 9,
 'PBB Rajapaksa': 9,
 'M Theekshana': 9,
 'V Shankar': 9,
 'CH Gayle': 9,
 'MR Marsh': 8,
 'SN Khan': 8,
 'SW Billings': 8,
 'AM Rahane': 8,
 'M Jansen': 8,
 'A Manohar': 8,
 'CJ Jordan': 8,
 'SPD Smith': 8,
 'SM Curran': 8,
 'OC McCoy': 7,
 'PK Garg': 7,
 'J Suchith': 7,
 'D Brevis': 7,
 'DP Conway': 7,
 'RK Singh': 7,
 'KR Sen': 7,
 'DT Christian': 7,
 'KA Jamieson': 7,
 'MJ Santner': 6,
 'Simarjeet Singh': 6,
 'R Dhawan': 6,
 'Kartik Tyagi': 6,
 'D Pretorius': 6,
 'OF Smith': 6,
 'NM Coulter-Nile': 6,
 'Shakib Al Hasan': 6,
 'KM Jadhav': 6,
 'R Sai Kishore': 5,
 'M Vohra': 5,
 'NT Ellis': 5,
 'Ramandeep Singh': 5,
 'HR Shokeen': 5,
 'JDS Neesham': 5,
 'SP Jackson': 5,
 'AJ Finch': 5,
 'B Sai Sudharsan': 5,
 'SS Prabhudessai': 5,
 'VG Arora': 5,
 'FA Allen': 5,
 'TS Mills': 5,
 'Basil Thampi': 5,
 'Akash Deep': 5,
 'AF Milne': 5,
 'GHS Garton': 5,
 'JJ Roy': 5,
 'MC Henriques': 5,
 'SS Tiwary': 5,
 'J Yadav': 5,
 'K Gowtham': 4,
 'K Kartikeya': 4,
 'RV Patel': 4,
 'Mandeep Singh': 4,
 'DJ Willey': 4,
 'Navdeep Saini': 4,
 'R Shepherd': 3,
 'Fazalhaq Farooqi': 3,
 'M Markande': 3,
 'HE van der Dussen': 3,
 'B Indrajith': 3,
 'PJ Sangwan': 3,
 'S Gopal': 3,
 'KK Nair': 3,
 'P Simran Singh': 3,
 'AJ Tye': 3,
 'SE Rutherford': 3,
 'TL Seifert': 3,
 'Anmolpreet Singh': 3,
 'GD Phillips': 3,
 'I Sharma': 3,
 'L Ngidi': 3,
 'A Mishra': 3,
 'Virat Singh': 3,
 'N Jagadeesan': 2,
 'PH Solanki': 2,
 'M Pathirana': 2,
 'T Stubbs': 2,
 'AS Roy': 2,
 'Harshit Rana': 2,
 'DJ Mitchell': 2,
 'DG Nalkande': 2,
 'Rasikh Salam': 2,
 'VR Aaron': 2,
 'RA Bawa': 2,
 'TU Deshpande': 2,
 'KL Nagarkoti': 2,
 'TK Curran': 2,
 'Mohammad Nabi': 2,
 'JA Richardson': 2,
 'CR Woakes': 2,
 'PN Mankad': 1,
 'A Tomar': 1,
 'R Sanjay Yadav': 1,
 'KS Sharma': 1,
 'SA Abbott': 1,
 'Aman Hakim Khan': 1,
 'PP Chawla': 1,
 'K Yadav': 1,
 'KM Asif': 1,
 'Akash Singh': 1,
 'S Sandeep Warrier': 1,
 'T Shamsi': 1,
 'IC Porel': 1,
 'AU Rashid': 1,
 'Sachin Baby': 1,
 'DJ Malan': 1,
 'DS Kulkarni': 1,
 'Imran Tahir': 1,
 'KW Richardson': 1,
 'Jalaj S Saxena': 1,
 'LI Meriwala': 1,
 'Harbhajan Singh': 1,
 'Mujeeb Ur Rahman': 1}

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [63]:
# code here
def matches_played(df,team):
    return df[(df.Team1==team) | (df.Team2==team)].shape[0]
def matches_won(df,team):
    return df[df.WinningTeam==team].shape[0]
def matches_no_result(df,team):
    return df[((df.Team1==team) | (df.Team2==team)) & (df.WinningTeam.isnull())].shape[0]
def point_table(season):
    df=matches[matches.Season==season]
    new_df=pd.DataFrame()
    new_df["Team"]=df.Team1.unique()
    new_df["Matches_Played"]=new_df.Team.apply(lambda x: matches_played(df,x))
    new_df["Matches_Won"]=new_df.Team.apply(lambda x: matches_won(df,x))
    new_df["Matches_NoResult"]=new_df.Team.apply(lambda x: matches_no_result(df,x))
    new_df["Points"]=new_df["Matches_Won"]*2+new_df["Matches_NoResult"]
    new_df.sort_values("Points",inplace=True,ascending=False)
    new_df.set_index("Team",inplace=True)
    return new_df
point_table("2022")

,Matches_Played,Matches_Won,Matches_NoResult,Points
Team,,,,
Gujarat Titans,16,12,0,24
Rajasthan Royals,17,10,0,20
Royal Challengers Bangalore,16,9,0,18
Lucknow Super Giants,15,9,0,18
Delhi Capitals,14,7,0,14
Punjab Kings,14,7,0,14
Sunrisers Hyderabad,14,6,0,12
Kolkata Knight Riders,14,6,0,12
Chennai Super Kings,14,4,0,8
Mumbai Indians,14,4,0,8

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [65]:
# code here
def point_table_extension(season):
    df3 = point_table(season)
    df = matches[matches.Season == season].copy()

    df3["SeasonPosition"] = df3.Points.rank(
        ascending=False,
        method='first'
    ).astype('object')

    df["LoosingTeam"] = pd.concat([
        df[df.WinningTeam == df.Team1]["Team2"],
        df[df.WinningTeam == df.Team2]["Team1"]
    ])

    final = df[df["MatchNumber"] == "Final"]
    wining_team = final.WinningTeam.values[0]
    runner = final.LoosingTeam.values[0]

    df3.at[wining_team, "SeasonPosition"] = "Winner"
    df3.at[runner, "SeasonPosition"] = "Runner"

    q = df[df["MatchNumber"] == "Qualifier 2"]
    e = df[df["MatchNumber"] == "Eliminator"]

    third = q.LoosingTeam.values[0]
    fourth = e.LoosingTeam.values[0]

    df3.at[third, "SeasonPosition"] = "Third"
    df3.at[fourth, "SeasonPosition"] = "Fourth"

    return df3

point_table_extension("2022")

,Matches_Played,Matches_Won,Matches_NoResult,Points,SeasonPosition
Team,,,,,
Gujarat Titans,16,12,0,24,Winner
Rajasthan Royals,17,10,0,20,Runner
Royal Challengers Bangalore,16,9,0,18,Third
Lucknow Super Giants,15,9,0,18,Fourth
Delhi Capitals,14,7,0,14,5.0
Punjab Kings,14,7,0,14,6.0
Sunrisers Hyderabad,14,6,0,12,7.0
Kolkata Knight Riders,14,6,0,12,8.0
Chennai Super Kings,14,4,0,8,9.0
Mumbai Indians,14,4,0,8,10.0